apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog-minio
  namespace: batch
data:
  minio.properties: |
    connector.name=hive

    hive.metastore=file
    hive.metastore.catalog.dir=file:///var/trino/minio-metastore
    hive.non-managed-table-creates-enabled=true
    hive.non-managed-table-writes-enabled=true

    fs.native-s3.enabled=true

    s3.endpoint=http://minio:9000
    s3.region=us-east-1
    s3.path-style-access=true
    s3.aws-access-key=minio
    s3.aws-secret-key=minio123