version: "3.9"

services:
  trino:
    container_name: datalake-trino
    image: "trinodb/trino:410"
    ports:
      - "8080:8080"              
    volumes:
      - ./trino/etc:/usr/lib/trino/etc:ro    
      - ./trino/catalog:/etc/trino/catalog   
    depends_on:
      - metastore_db
      - hive-metastore

  metastore_db:
    container_name: datalake-metastore-db
    image: postgres:15           
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - /mnt/volume_sgp1_01/metastore_pgdata:/var/lib/postgresql/data

  hive-metastore:
    container_name: datalake-hive-metastore
    image: "starburstdata/hive:3.1.2-e.18"             
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive

      S3_ENDPOINT: http://192.168.49.2:30900
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_PATH_STYLE_ACCESS: "true"

      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
    depends_on:
      - metastore_db

  grafana:
    container_name: datalake-grafana
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "trino-datasource"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "trino-datasource"
    volumes:
      - /mnt/volume_sgp1_01/grafana-data:/var/lib/grafana
    depends_on:
      - trino
